library(ggplot2)
library(dplyr)
library(ggpubr)
library(gridExtra)


##countsdata is the countsdata.txt file generated by reformat.sh
countsdatafile <- countsdata


##add individual ids, viral read counts, tissue
countsdatafile$Individual <- ifelse(countsdatafile$V9 == "A0078" |countsdatafile$V9 =="A0079"|countsdatafile$V9 =="A0080"|countsdatafile$V9 =="A0312", 'RA1779',
                                 ifelse(countsdatafile$V9 == "A0318"|countsdatafile$V9 =="A0192"|countsdatafile$V9 =="A0191"|countsdatafile$V9 =="A0190",'RA0917', NA))

countsdatafile$viralReadCount <- ifelse(countsdatafile$V9 == "A0078", 34989,
                                     ifelse(countsdatafile$V9 == "A0079", 4895,
                                            ifelse(countsdatafile$V9 == "A0080", 108787,
                                                   ifelse(countsdatafile$V9 == "A0312", 45015,
                                                          ifelse(countsdatafile$V9 == "A0318", 258045,
                                                                 ifelse(countsdatafile$V9 == "A0192", 2764772,
                                                                        ifelse(countsdatafile$V9 == "A0191", 450471,
                                                                               ifelse(countsdatafile$V9 == "A0190", 925085, NA))))))))


countsdatafile$Tissue <- ifelse(countsdatafile$V9 =="A0190"|countsdatafile$V9 =="A0078", 'LN (ax)',
                             ifelse(countsdatafile$V9 =="A0079" |countsdatafile$V9 =="A0191", 'LN (ing)',
                                    ifelse(countsdatafile$V9 == "A0080" |countsdatafile$V9 =="A0192", 'LN (mes)',
                                           ifelse(countsdatafile$V9 == "A0312" |countsdatafile$V9 =="A0318",'Whole Blood', NA))))
##add normalized counts
countsdatafile$normalizedcounts <- countsdatafile$V7/countsdatafile$viralReadCount

##check for null values
countsdatafile[!complete.cases(countsdatafile), ]

##overviewplot
dvgtypes <- countsdatafile$V1
tissuetypes <-countsdatafile$Tissue
animalids <- countsdatafile$Individual

pr3 <- ggplot(data=countsdatafile, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

pnr3 <- ggplot(data=countsdatafile, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

panimalr3 <- ggplot(data=countsdatafile, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=animalids)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set1") + theme_minimal() + labs(fill = "Animal IDs")

panimalnr3 <- ggplot(data=countsdatafile, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=animalids)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set1") + theme_minimal() + labs(fill = "Animal IDs")

ptissuer3 <- ggplot(data=countsdatafile, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=tissuetypes)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set2") + theme_minimal() + labs(fill = "Tissue Types")

ptissuenr3 <- ggplot(data=countsdatafile, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=tissuetypes)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set2") + theme_minimal() + labs(fill = "Tissue Types")

##animalplots
df0917r3 <- subset(countsdatafile, Individual == 'RA0917')
dvgtypes0917r3 <- df0917r3$V1
df1779r3 <- subset(countsdatafile, Individual == 'RA1779')
dvgtypes1779r3 <- df1779r3$V1

p0917r3 <- ggplot(data=df0917r3, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for RA0917") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes0917r3)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

p0917nr3 <- ggplot(data=df0917r3, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for RA0917") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes0917r3)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

p1779r3 <- ggplot(data=df1779r3, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for RA1779") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes1779r3)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

p1779nr3 <- ggplot(data=df1779r3, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for RA1779") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes1779r3)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

##tissueplots
dflnaxr3 <- subset(countsdatafile, Tissue == 'LN (ax)')
dvgtypes_lnaxr3 <- dflnaxr3$V1
dflninr3 <- subset(countsdatafile, Tissue == 'LN (ing)')
dvgtypes_lninr3 <- dflninr3$V1
dflnmesr3 <- subset(countsdatafile, Tissue == 'LN (mes)')
dvgtypes_lnmesr3 <- dflnmesr3$V1
dfwbr3 <- subset(countsdatafile, Tissue == 'Whole Blood')
dvgtypes_wbr3 <- dfwbr3$V1

plnaxr3 <- ggplot(data=dflnaxr3, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Lymph Node (ax)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnaxr3)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plnaxnr3 <- ggplot(data=dflnaxr3, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Lymph Node (ax)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnaxr3)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plninr3 <- ggplot(data=dflninr3, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Lymph Node (in)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lninr3)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plninnr3 <- ggplot(data=dflninr3, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Lymph Node (in)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lninr3)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plnmesr3 <- ggplot(data=dflnmesr3, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Lymph Node (mes)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnmesr3)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plnmesnr3 <- ggplot(data=dflnmesr3, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Lymph Node (mes)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnmesr3)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

pwbr3 <- ggplot(data=dfwbr3, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbr3)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

pwbnr3 <- ggplot(data=dfwbr3, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbr3)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")



##countsdata is the counts.txt file generated by reformat.sh
cdatacopyR1 <- countsdata_march22R1


##add individual ids, viral read counts, tissue
cdatacopyR1$Individual <- ifelse(cdatacopyR1$V9 == "A0078" |cdatacopyR1$V9 =="A0079"|cdatacopyR1$V9 =="A0080"|cdatacopyR1$V9 =="A0312", 'RA1779',
                                 ifelse(cdatacopyR1$V9 == "A0318"|cdatacopyR1$V9 =="A0192"|cdatacopyR1$V9 =="A0191"|cdatacopyR1$V9 =="A0190",'RA0917', NA))

cdatacopyR1$viralReadCount <- ifelse(cdatacopyR1$V9 == "A0078", 34989,
                                     ifelse(cdatacopyR1$V9 == "A0079", 4895,
                                            ifelse(cdatacopyR1$V9 == "A0080", 108787,
                                                   ifelse(cdatacopyR1$V9 == "A0312", 45015,
                                                          ifelse(cdatacopyR1$V9 == "A0318", 258045,
                                                                 ifelse(cdatacopyR1$V9 == "A0192", 2764772,
                                                                        ifelse(cdatacopyR1$V9 == "A0191", 450471,
                                                                               ifelse(cdatacopyR1$V9 == "A0190", 925085, NA))))))))


cdatacopyR1$Tissue <- ifelse(cdatacopyR1$V9 =="A0190"|cdatacopyR1$V9 =="A0078", 'LN (ax)',
                             ifelse(cdatacopyR1$V9 =="A0079" |cdatacopyR1$V9 =="A0191", 'LN (ing)',
                                    ifelse(cdatacopyR1$V9 == "A0080" |cdatacopyR1$V9 =="A0192", 'LN (mes)',
                                           ifelse(cdatacopyR1$V9 == "A0312" |cdatacopyR1$V9 =="A0318",'Whole Blood', NA))))
##add normalized counts
cdatacopyR1$normalizedcounts <- cdatacopyR1$V7/cdatacopyR1$viralReadCount

##check for null values
cdatacopyR1[!complete.cases(cdatacopyR1), ]

##overviewplot
dvgtypes <- cdatacopyR1$V1
tissuetypes <-cdatacopyR1$Tissue
animalids <- cdatacopyR1$Individual

pr1 <- ggplot(data=cdatacopyR1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

pnr1 <- ggplot(data=cdatacopyR1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

panimalr1 <- ggplot(data=cdatacopyR1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=animalids)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set1") + theme_minimal() + labs(fill = "Animal IDs")

panimalnr1 <- ggplot(data=cdatacopyR1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=animalids)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set1") + theme_minimal() + labs(fill = "Animal IDs")

ptissuer1 <- ggplot(data=cdatacopyR1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=tissuetypes)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set2") + theme_minimal() + labs(fill = "Tissue Types")

ptissuenr1 <- ggplot(data=cdatacopyR1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints Across 8 Samples") + geom_bar(stat="identity", width = 15, aes(fill=tissuetypes)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Set2") + theme_minimal() + labs(fill = "Tissue Types")

##animalplots
df0917r1 <- subset(cdatacopyR1, Individual == 'RA0917')
dvgtypes0917r1 <- df0917r1$V1
df1779r1 <- subset(cdatacopyR1, Individual == 'RA1779')
dvgtypes1779r1 <- df1779r1$V1

p0917r1 <- ggplot(data=df0917r1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for RA0917") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes0917r1)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

p0917nr1 <- ggplot(data=df0917r1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for RA0917") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes0917r1)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

p1779r1 <- ggplot(data=df1779r1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for RA1779") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes1779r1)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

p1779nr1 <- ggplot(data=df1779r1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for RA1779") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes1779r1)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

##tissueplots
dflnaxr1 <- subset(cdatacopyR1, Tissue == 'LN (ax)')
dvgtypes_lnaxr1 <- dflnaxr1$V1
dflninr1 <- subset(cdatacopyR1, Tissue == 'LN (ing)')
dvgtypes_lninr1 <- dflninr1$V1
dflnmesr1 <- subset(cdatacopyR1, Tissue == 'LN (mes)')
dvgtypes_lnmesr1 <- dflnmesr1$V1
dfwbr1 <- subset(cdatacopyR1, Tissue == 'Whole Blood')
dvgtypes_wbr1 <- dfwbr1$V1

plnaxr1 <- ggplot(data=dflnaxr1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Lymph Node (ax)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnaxr1)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plnaxnr1 <- ggplot(data=dflnaxr1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Lymph Node (ax)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnaxr1)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plninr1 <- ggplot(data=dflninr1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Lymph Node (in)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lninr1)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plninnr1 <- ggplot(data=dflninr1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Lymph Node (in)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lninr1)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plnmesr1 <- ggplot(data=dflnmesr1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Lymph Node (mes)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnmesr1)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

plnmesnr1 <- ggplot(data=dflnmesr1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Lymph Node (mes)") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnmesr1)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

pwbr1 <- ggplot(data=dfwbr1, aes(x=V3, y=V7)) + 
  ggtitle("DVG Breakpoints for Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbr1)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

pwbnr1 <- ggplot(data=dfwbr1, aes(x=V3, y=normalizedcounts)) + 
  ggtitle("DVG Breakpoints for Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbr1)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")

#mergedcdata
cdatacopymerge <- merge(cdatacopyR1,countsdatafile)

# ##three animals --> one tissue (whole bloo)
# dfwbRA1818 <- subset(dfwb, Individual == 'RA1818')
# dvgtypes_wbRA1818 <- dfwbRA1818$V1
# 
# pwbRA1818 <- ggplot(data=dfwbRA1818, aes(x=V3, y=V7)) + 
#   ggtitle("RA1818 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1818)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# pwbRA1818n <- ggplot(data=dfwbRA1818, aes(x=V3, y=normalizedcounts)) + 
#   ggtitle("RA1818 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1818)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# 
# dfwbRA1423 <- subset(dfwb, Individual == 'RA1423')
# dvgtypes_wbRA1423 <- dfwbRA1423$V1
# 
# pwbRA1423 <- ggplot(data=dfwbRA1423, aes(x=V3, y=V7)) + 
#   ggtitle("RA1423 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1423)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# pwbRA1423n <- ggplot(data=dfwbRA1423, aes(x=V3, y=normalizedcounts)) + 
#   ggtitle("RA1423 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1423)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# 
# dfwbRA1074 <- subset(dfwb, Individual == 'RA1423')
# dvgtypes_wbRA1074 <- dfwbRA1074$V1
# 
# pwbRA1074 <- ggplot(data=dfwbRA1074, aes(x=V3, y=V7)) + 
#   ggtitle("RA1074 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1074)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# pwbRA1074n <- ggplot(data=dfwbRA1074, aes(x=V3, y=normalizedcounts)) + 
#   ggtitle("RA1074 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1074)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# ## one animal (RA1423) --> 3 tissues
# ##whole blood from 1423 is done in 3 animals --> 1 tissue; it is dfwbRA1423 and associated plots
# dfwbRA1423 <- subset(dfwb, Individual == 'RA1423')
# dvgtypes_wbRA1423 <- dfwbRA1423$V1
# 
# pwbRA1423 <- ggplot(data=dfwbRA1423, aes(x=V3, y=V7)) + 
#   ggtitle("RA1423 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1423)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# pwbRA1423n <- ggplot(data=dfwbRA1423, aes(x=V3, y=normalizedcounts)) + 
#   ggtitle("RA1423 Whole Blood") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_wbRA1423)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# 
# dflnRA1423 <- subset(dfln, Individual == 'RA1423')
# dvgtypes_lnRA1423 <- dflnRA1423$V1
# 
# plnRA1423 <- ggplot(data=dflnRA1423, aes(x=V3, y=V7)) + 
#   ggtitle("RA1423 Lymph Node") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnRA1423)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# plnRA1423n <- ggplot(data=dflnRA1423, aes(x=V3, y=normalizedcounts)) + 
#   ggtitle("RA1423 Lymph Node") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_lnRA1423)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(labels = label_scientific(), breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# 
# dfkidneyRA1423 <- subset(dfkidney, Individual == 'RA1423')
# dvgtypes_kidneyRA1423 <- dfkidneyRA1423$V1
# 
# pkidneyRA1423 <- ggplot(data=dfkidneyRA1423, aes(x=V3, y=V7)) + 
#   ggtitle("RA1423 Kidney") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_kidneyRA1423)) + xlab("Breakpoint Position (bases)") + ylab("# of Reads") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# pkidneyRA1423n <- ggplot(data=dfkidneyRA1423, aes(x=V3, y=normalizedcounts)) + 
#   ggtitle("RA1423 Kidney") + geom_bar(stat="identity", width = 15, aes(fill=dvgtypes_kidneyRA1423)) + xlab("Breakpoint Position (bases)") + ylab("Normalized Read Counts") + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + 
#   scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + scale_fill_brewer(palette = "Paired") + theme_minimal() + labs(fill = "DVG Types")
# 
# 
# 


##plot lists
OverviewAnimalPlotsR1 <- list(panimalr1, panimalnr1)
AnimalPlotsR1 <- list(p0917r1, p1779r1)
NormalizedAnimalPlotsR1 <- list(p0917nr1,p1779nr1)
OverviewTissuePlotsR1 <- list(ptissuer1,ptissuenr1)
LNaxR1 <- list(plnaxr1, plnaxnr1)
LNinR1 <- list(plninr1, plninnr1)
LNmesR1 <- list(plnmesr1, plnmesnr1)
WholeBloodR1 <- list(pwbr1, pwbnr1)

OverviewPlotsR3 <- list(pr3,pnr3)
OverviewAnimalPlotsR3 <- list(panimalr3, panimalnr3)
AnimalPlotsR3 <- list(p0917r3, p1779r3)
NormalizedAnimalPlotsR3 <- list(p0917nr3,p1779nr3)
OverviewTissuePlotsR3 <- list(ptissuer3,ptissuenr3)
LNaxR3 <- list(plnaxr3, plnaxnr3)
LNinR3 <- list(plninr3, plninnr3)
LNmesR3 <- list(plnmesr3, plnmesnr3)
WholeBloodR3 <- list(pwbr3, pwbnr3)
OverviewPlotsR1 <- list(pr1,pnr1)


PlotList <- list(OverviewPlotsR1, OverviewAnimalPlotsR1, AnimalPlotsR1, NormalizedAnimalPlotsR1, OverviewTissuePlotsR1, LNaxR1,LNinR1, LNmesR1,WholeBloodR1, OverviewPlotsR3, OverviewAnimalPlotsR3, AnimalPlotsR3, NormalizedAnimalPlotsR3, OverviewTissuePlotsR3, LNaxR1,LNinR3, LNmesR3,WholeBloodR3)


## plots --> pdf
pdf("plotsbothreads.pdf", onefile = TRUE)
for (i in seq(length(PlotList))) {
  do.call("grid.arrange", PlotList[[i]])
}
dev.off()